<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNy9nxlm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNy9nxlm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNy9nxlm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNy9nxlm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNy9nxlm\appDevDebugProjectContainer([
    'container.build_hash' => 'Ny9nxlm',
    'container.build_id' => 'b19378d5',
    'container.build_time' => 1566564200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNy9nxlm');
